{
 "title": "Vault and Consul",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "vault: update auth token (5s rate)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(vault_route_update_auth_token__count[5s])"
    }
   ]
  },
  {
   "title": "vault: consul put (5s rate)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(vault_consul_put_count[1m])"
    }
   ]
  },
  {
   "title": "host: cpu",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg without (cpu)(irate(node_cpu_seconds_total{mode!=\"idle\"}[5s]))"
    }
   ]
  },
  {
   "title": "host: disk I/O utilization",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total[5s])"
    }
   ]
  }
 ]
}