{
 "title": "Node Exporter",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   {
    "name": "job",
    "query": "node_exporter-core,node_exporter"
   },
   {
    "name": "instance",
    "query": "label_values(up{job=~\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "$instance CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "repeat": "instance",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg without (cpu) (irate(node_cpu_seconds_total{instance=~\"($instance).*\",mode!=\"idle\"}[5m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "$instance Disk",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "repeat": "instance",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=~\"($instance).*\",device!~\"^(md[0-9]+$|dm-)\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "$instance RAM",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "repeat": "instance",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"($instance).*\"}\n         - node_memory_MemFree_bytes{instance=~\"($instance).*\"}\n         - node_memory_Buffers_bytes{instance=~\"($instance).*\"}\n         - node_memory_Cached_bytes{instance=~\"($instance).*\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~\"($instance).*\"}\n                    + node_memory_Cached_bytes{instance=~\"($instance).*\"}",
     "legendFormat": "Buffers+Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"($instance).*\"}",
     "legendFormat": "Free"
    }
   ]
  }
 ]
}