{
 "title": "Nomad Servers",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "nomad up",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(up{job=\"nomad-servers\"})"
    }
   ]
  },
  {
   "title": "broker ready",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nomad_nomad_broker_total_ready)"
    }
   ]
  },
  {
   "title": "broker unacked",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nomad_nomad_broker_total_unacked)"
    }
   ]
  },
  {
   "title": "broker blocked",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nomad_nomad_broker_total_blocked)"
    }
   ]
  },
  {
   "title": "raft: GC pausing over prev minute",
   "type": "graph",
   "description": "Indicator of memory pressure. See [doc](https://www.nomadproject.io/docs/telemetry/index.html)",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "sum without(job) (rate(nomad_runtime_total_gc_pause_ns{job=\"nomad-servers\"}[1m]))/1000000"
    }
   ]
  },
  {
   "title": "raft: rpc request rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum without(job) (rate(nomad_nomad_rpc_request[1m]))"
    }
   ]
  },
  {
   "title": "raft: rpc request error rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum without(job) (rate(nomad_nomad_rpc_request_error[1m]))"
    }
   ]
  },
  {
   "title": "raft: time for leader to contact followers - 99th%",
   "type": "graph",
   "description": "General indicator of Raft latency. See [doc](https://www.nomadproject.io/docs/telemetry/index.html)",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "sum without(job,quantile) (nomad_raft_leader_lastContact{quantile=\"0.99\"})"
    }
   ]
  },
  {
   "title": "raft: append time - 99th%",
   "type": "graph",
   "description": "General indicator of Raft latency.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "sum without(job,quantile) (nomad_raft_replication_appendEntries_rpc{quantile=\"0.99\"})"
    }
   ]
  }
 ]
}