{
 "title": "Process Exporter Storage",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   {
    "name": "instance",
    "query": "label_values(namedprocess_scrape_errors{job=~\"process-exporter.*\"}, instance)"
   },
   {
    "name": "group",
    "query": "label_values(namedprocess_namegroup_num_procs{job=~\"process-exporter.*\", instance=~\"($instance)\"}, groupname)"
   }
  ]
 },
 "panels": [
  { "title": "Group memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Resident memory",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (groupname) (\n            namedprocess_namegroup_memory_bytes{memtype=\"resident\", groupname=~\"$group\", instance=~\"$instance\"}\n          )",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Virtual memory",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (groupname) (\n            namedprocess_namegroup_memory_bytes{memtype=\"virtual\", groupname=~\"$group\", instance=~\"$instance\"}\n          )",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Swapped memory",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (groupname) (\n            namedprocess_namegroup_memory_bytes{memtype=\"swapped\", groupname=~\"$group\", instance=~\"$instance\"}\n          )",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  { "title": "Group Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Disk Read",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum by (groupname) (\n            irate(namedprocess_namegroup_read_bytes_total{groupname=~\"$group\", instance=~\"$instance\"}[1m])\n          )",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Disk Write",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum by (groupname) (\n            irate(namedprocess_namegroup_write_bytes_total{groupname=~\"$group\", instance=~\"$instance\"}[1m])\n          )",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Major page faults",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (groupname) (\n            irate(namedprocess_namegroup_major_page_faults_total{groupname=~\"$group\", instance=~\"$instance\"}[1m])\n          )",
     "legendFormat": "{{groupname}}"
    }
   ]
  }
 ]
}