{
 "title": "Process Exporter Detail",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   {
    "name": "instance",
    "query": "label_values(namedprocess_scrape_errors{job=~\"process-exporter.*\"}, instance)"
   },
   {
    "name": "group",
    "query": "label_values(namedprocess_namegroup_num_procs{job=~\"process-exporter.*\", instance=~\"($instance)\"}, groupname)"
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU User",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (groupname) (\n            irate(namedprocess_namegroup_cpu_user_seconds_total{groupname=~\"$group\", instance=~\"$instance\"}[1m])\n          )",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "CPU System",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (groupname) (\n            irate(namedprocess_namegroup_cpu_system_seconds_total{groupname=~\"$group\", instance=~\"$instance\"}[1m])\n          )",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Context switches",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (groupname) (\n            irate(namedprocess_namegroup_context_switches_total{groupname=~\"$group\", instance=~\"$instance\"}[1m])\n          )",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  { "title": "Processes and Threads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Num processes",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (groupname) (\n            namedprocess_namegroup_num_procs{groupname=~\"$group\", instance=~\"$instance\"}\n          )",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Num threads",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (groupname) (\n            namedprocess_namegroup_num_threads{groupname=~\"$group\", instance=~\"$instance\"}\n          )",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Exits/Restarts",
   "type": "graph",
   "description": "These represent changes to the oldest start time in the group.\n        When there is a single process in the group this must mean it restarted.\n        With multiple processes it's more ambiguous: it could just mean that the\n        oldest one exited and no new process has started.",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum by (groupname) (\n            changes(namedprocess_namegroup_oldest_start_time_seconds{groupname=~\"$group\", instance=~\"$instance\"}[1m])\n          )",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  { "title": "Filedescs and waits", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Open filedescs",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (groupname) (\n            namedprocess_namegroup_open_filedesc{groupname=~\"$group\", instance=~\"$instance\"}\n          )",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Worst filedesc ratio",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (groupname) (\n            namedprocess_namegroup_worst_fd_ratio{groupname=~\"$group\", instance=~\"$instance\"}\n          )",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Wchan threads",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (groupname, wchan) (\n            namedprocess_namegroup_threads_wchan{groupname=~\"$group\", instance=~\"$instance\"}\n          )",
     "legendFormat": "{{groupname}} {{wchan}}"
    }
   ]
  }
 ]
}