{
 "title": "Process Exporter",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   {
    "name": "instance",
    "query": "label_values(namedprocess_scrape_errors{job=~\"process-exporter.*\"}, instance)"
   },
   {
    "name": "group",
    "query": "label_values(namedprocess_namegroup_num_procs{job=~\"process-exporter.*\", instance=~\"($instance)\"}, groupname)"
   }
  ]
 },
 "panels": [
  { "title": "Monitoring status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "process_exporter up",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{job=~\"process-exporter.*\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "scrape duration",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "scrape_duration_seconds{job=~\"process-exporter.*\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "process scrape errors",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(namedprocess_scrape_errors{instance=~\"$instance\"}[1m])"
    },
    {
     "expr": "rate(namedprocess_scrape_partial_errors{instance=~\"$instance\"}[1m])"
    },
    {
     "expr": "rate(namedprocess_scrape_procread_errors{instance=~\"$instance\"}[1m])"
    }
   ]
  },
  { "title": "Group status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 15, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (groupname) (\n            irate(namedprocess_namegroup_cpu_system_seconds_total{groupname=~\"$group\", instance=~\"$instance\"}[1m])\n            + irate(namedprocess_namegroup_cpu_user_seconds_total{groupname=~\"$group\", instance=~\"$instance\"}[1m])\n          )",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Resident memory",
   "type": "graph",
   "gridPos": { "h": 15, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (groupname) (\n            namedprocess_namegroup_memory_bytes{memtype=\"resident\", groupname=~\"$group\", instance=~\"$instance\"}\n          )",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 15, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum by (groupname) (\n            irate(namedprocess_namegroup_write_bytes_total{groupname=~\"$group\", instance=~\"$instance\"}[1m])\n            + irate(namedprocess_namegroup_read_bytes_total{groupname=~\"$group\", instance=~\"$instance\"}[1m])\n          )",
     "legendFormat": "{{groupname}}"
    }
   ]
  }
 ]
}