{
 "title": "Raspberry Pi",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   {
    "name": "instance",
    "query": "label_values(rpi_throttled, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "rpi_temperature_celsius{instance=~\"($instance).*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Throttled",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "hex0x" }
   ],
   "targets": [
    {
     "expr": "rpi_throttled{instance=~\"($instance).*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "rpi_voltage_volts{instance=~\"($instance).*\"}",
     "legendFormat": "{{instance}} {{component}}"
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "rpi_frequency_hz{instance=~\"($instance).*\"}",
     "legendFormat": "{{instance}} {{component}}"
    }
   ]
  }
 ]
}