{
 "title": "Vault on Consul",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   { "name": "interval", "query": "10s,30s,1m,5m,15m" },
   { "name": "quantile", "query": "0.5,0.9,0.99" }
  ]
 },
 "panels": [
  { "title": "Node stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg without (cpu) (rate(node_cpu_seconds_total{mode!=\"idle\"}[5m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{device!~\"^(md[0-9]+$|dm-)\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "description": "Negative=transmit, Positive=receive",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total[$interval])",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "-rate(node_network_transmit_bytes_total[$interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes\n         - node_memory_MemFree_bytes\n         - node_memory_Buffers_bytes\n         - node_memory_Cached_bytes",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers_bytes\n                    + node_memory_Cached_bytes",
     "legendFormat": "Buffers+Cached"
    },
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "Free" }
   ]
  },
  { "title": "Vault Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Request $interval Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(vault_core_handle_request_count[$interval])"
    }
   ]
  },
  {
   "title": "Handle Request Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "vault_core_handle_request{quantile=~\"$quantile\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Check Token Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "vault_core_check_token{quantile=~\"$quantile\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Fetch ACL and Token Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "vault_core_fetch_acl_and_token{quantile=~\"$quantile\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  { "title": "Consul Backend Timing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "consul GET",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "vault_consul_get{quantile=~\"$quantile\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "consul PUT",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "vault_consul_put{quantile=~\"$quantile\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "consul LIST",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "vault_consul_list{quantile=~\"$quantile\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "consul DELETE",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "vault_consul_delete{quantile=~\"$quantile\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  { "title": "Consul Backend Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "consul GET rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(vault_consul_get_count[$interval])"
    }
   ]
  },
  {
   "title": "consul PUT rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 17 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(vault_consul_put_count[$interval])"
    }
   ]
  },
  {
   "title": "consul LIST rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(vault_consul_list_count[$interval])"
    }
   ]
  },
  {
   "title": "consul DELETE rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 17 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(vault_consul_delete_count[$interval])"
    }
   ]
  }
 ]
}